app/controller/routes.py
import os
import re
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, session, render_template_string, send_from_directory, current_app, flash
# 從 models.py 導入所有資料庫相關函式
from ..model.models import get_account_by_account, get_professors, get_professor_by_id, get_otherinfo, get_professor_by_account_id, get_appointmentslot, update_appointment_slots, update_notice, update_lab_rule, update_research_area, get_student_count, get_student_by_account_id, update_student_profile, update_professor_profile, get_account_by_account_id, update_appointment_status, get_appointments_by_student, get_appointments_by_professor, create_appointment, get_all_professors, get_all_students, delete_student, delete_professor, create_student_account, create_pro_account,  get_all_professor_names, create_mentorship_request, get_professor_id_by_name, get_student_mentorship_requests, get_student_id_by_account_id, get_professor_mentorship_requests, update_mentorship_request_status, get_professor_mentorship_history, check_student_mentorship_status, update_reservationOpen_status, check_existing_student, check_existing_account, check_existing_location
from werkzeug.utils import secure_filename
from datetime import datetime

# 創建 Blueprint 實例
main = Blueprint('main', __name__)

# 設定上傳檔案相關常數
UPLOAD_FOLDER = 'app/static/img'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@main.route("/")
def index():
    return redirect(url_for('main.login'))

# 學生修改資料


@main.route('/profile_stu_fix')
def profile_stu_fix():
    account_id = session.get('user_id')
    student = get_student_by_account_id(account_id)
    account = get_account_by_account_id(account_id)
    return render_template('profile_stu_fix.html', student=student, account=account)


@main.route('/profile_stu')
def profile_stu():
    account_id = session.get('user_id')
    student = get_student_by_account_id(account_id)
    return render_template('profile_stu.html', student=student)


@main.route('/update_profile', methods=['POST'])
def update_profile():
    account_id = session.get('user_id')
    name = request.form['name']
    password = request.form['password']
    account = request.form['account']
    email = request.form['email']
    phone = request.form['phone']

    # 獲取教授資料
    student = get_student_by_account_id(account_id)
    student_id = student[7]  # 假設 professorID 是第一個字段

    photo = None

    # 處理文件上傳
    if 'photo' in request.files:
        file = request.files['photo']
        if file and allowed_file(file.filename):
            ext = file.filename.rsplit('.', 1)[1].lower()
            print(f"ext: {ext}")
            filename = f"student_{student_id}.{ext}"

            # filename = secure_filename(file.filename)
            file.save(os.path.join(UPLOAD_FOLDER, filename))
            photo = filename
        else:
            photo = None
    else:
        photo = None

    update_student_profile(account_id, name, password,
                           account, email, phone, photo)
    return redirect(url_for('main.profile_stu'))

# 教授修改資料


@main.route('/profile_pro')
def profile_pro():
    account_id = session.get('user_id')
    professor = get_professor_by_account_id(account_id)
    return render_template('profile_pro.html', professor=professor)


@main.route('/profile_pro_fix')
def profile_pro_fix():
    account_id = session.get('user_id')
    professor = get_professor_by_account_id(account_id)
    account = get_account_by_account_id(account_id)
    # print(f"account: {account}")
    # print(f"professor: {professor}")
    return render_template('profile_pro_fix.html', professor=professor, account=account)


@main.route('/update_pro_profile', methods=['POST'])
def update_pro_profile():
    account_id = session.get('user_id')
    name = request.form['name']
    password = request.form['password']
    account = request.form['account']
    professorship = request.form['professorship']
    email = request.form['email']
    phone = request.form['phone']
    # print(f"request.files: {request.files}")

    # 獲取教授資料
    professor = get_professor_by_account_id(account_id)
    professor_id = professor[0]  # 假設 professorID 是第一個字段

    photo = None

    # 處理文件上傳
    if 'photo' in request.files:
        file = request.files['photo']
        if file and allowed_file(file.filename):
            ext = file.filename.rsplit('.', 1)[1].lower()
            print(f"ext: {ext}")
            filename = f"professor_{professor_id}.{ext}"

            # filename = secure_filename(file.filename)
            file.save(os.path.join(UPLOAD_FOLDER, filename))
            photo = filename
        else:
            photo = None
    else:
        photo = None

    update_professor_profile(account_id, name, password,
                             account, professorship, email, phone, photo)
    return redirect(url_for('main.profile_pro'))

# 新增登入功能


@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        account = request.form['account']
        password = request.form['password']
        user = get_account_by_account(account)
        # print(f"user_account: {user.account}")
        # print(f"user_password: {user.password}")
        # print(f"password: {password}")
        # print(user.password==password)
        if user and user.password == password:
            session['user_id'] = user.accountID
            session['role'] = user.role
            if user.role == 0:
                return redirect(url_for('main.student_dashboard'))
            elif user.role == 1:
                return redirect(url_for('main.teacher_dashboard'))
            elif user.role == 2:
                return redirect(url_for('main.account_stu'))
        elif user:
            return render_template_string('''
                    <script>
                        alert('密碼錯誤');
                        window.location.href = '/';
                    </script>
                ''')
        elif user == None:
            return render_template_string('''
                <script>
                    alert('查無此帳號');
                    window.location.href = '/';
                </script>
            ''')
    return render_template('login.html')

# 登出


@main.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('main.login'))


# 學生登入後介面
@main.route('/student_dashboard')
def student_dashboard():
    if 'role' in session and session['role'] == 0:
        p = get_professors()
        professors = get_all_professors()
        # print(professors)
        # print(p)
        return render_template('student_dashboard.html', professors=professors)
    return redirect(url_for('main.login'))


@main.route("/view_pro_detail/<int:professor_id>")
def view_pro_detail(professor_id):
    professor = get_professor_by_id(professor_id)
    otherinfo = get_otherinfo(professor_id)
    appointmentslot = get_appointmentslot(professor_id)
    student_count = get_student_count(professor_id)
    # print(professor)
    # print(otherinfo)
    # print(appointmentslot)
    return render_template('view_pro_detail.html', professor=professor, otherinfo=otherinfo, appointmentslot=appointmentslot, student_count=student_count)

# 老師登入後介面


@main.route('/teacher_dashboard')
def teacher_dashboard():
    if 'role' in session and session['role'] == 1:
        account_id = session.get('user_id')
        professor = get_professor_by_account_id(account_id)
        otherinfo = get_otherinfo(professor[0])
        appointmentslot = get_appointmentslot(professor[0])
        student_count = get_student_count(professor[0])
        # print(professor)
        # print(appointmentslot)
        return render_template('teacher_dashboard.html', professor=professor, otherinfo=otherinfo, appointmentslot=appointmentslot, student_count=student_count)
    return redirect(url_for('main.login'))


@main.route('/update_appointment_slots', methods=['POST'])
def update_appointment_slots_route():
    account_id = session.get('user_id')
    professor = get_professor_by_account_id(account_id)
    new_slot = request.form['appointment_slot']
    # professor[0] 是 professorID
    update_appointment_slots(professor[0], new_slot)
    return redirect(url_for('main.teacher_dashboard'))


@main.route('/update_lab_rule', methods=['POST'])
def update_lab_rule_route():
    account_id = session.get('user_id')
    professor = get_professor_by_account_id(account_id)
    new_lab_rule = request.form['lab_rule_content']
    update_lab_rule(professor[0], new_lab_rule)  # professor[0] 是 professorID
    return redirect(url_for('main.teacher_dashboard'))


@main.route('/update_notice', methods=['POST'])
def update_notice_route():
    account_id = session.get('user_id')
    professor = get_professor_by_account_id(account_id)
    new_notice = request.form['notice_content']
    update_notice(professor[0], new_notice)  # professor[0] 是 professorID
    return redirect(url_for('main.teacher_dashboard'))


@main.route('/update_research_area', methods=['POST'])
def update_research_area_route():
    account_id = session.get('user_id')
    professor = get_professor_by_account_id(account_id)
    new_research_area = request.form['research_area_content']
    # professor[0] 是 professorID
    update_research_area(professor[0], new_research_area)
    return redirect(url_for('main.teacher_dashboard'))


@main.route('/update_reservationOpen_status', methods=['POST'])
def update_reservationOpen_status_route():
    account_id = session.get('user_id')
    professor = get_professor_by_account_id(account_id)
    new_status = request.form['appointment_status']

app/templates/profile_pro_fix.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>NCUIM指導教授管理預約系統</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{{ url_for('static', filename='lib/lightbox/css/lightbox.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">

        <!-- Customized Bootstrap Stylesheet -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    </head>

    <body>

        <!-- Navbar start -->
        <div class="container-fluid fixed-top">
            <div class="container px-0">
                <nav class="navbar navbar-light bg-white navbar-expand-xl">
                    <a href="index" class="navbar-brand"><h1 class="text-primary display-6">指導教授管理預約系統</h1></a>
                    <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="fa fa-bars text-primary"></span>
                    </button>
                    <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                        <div class="navbar-nav mx-auto">
                            <a href="{{ url_for('main.teacher_dashboard') }}" class="nav-item nav-link">研究室資訊</a>
                            <a href="{{ url_for('main.appointment_teacher') }}" class="nav-item nav-link">預約紀錄</a>
                            <a href="{{ url_for('main.mentorship_pro') }}" class="nav-item nav-link">指導邀請</a>
                            <a href="{{ url_for('main.mentorship_pro_detail') }}" class="nav-item nav-link">指導邀請紀錄</a>
                        </div>
                        <div class="d-flex m-3 me-0">
                            <a href="profile_pro" class="my-auto" title="帳號管理">
                                <i class="fas fa-user fa-2x"></i>
                            </a>
                            <a href="{{ url_for('main.logout') }}" class="btn btn-danger ms-3">登出</a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Navbar End -->


        <!-- Single Product Start -->
        <div class="container-fluid py-0">
            <!-- 顏色區塊 Start -->
            <div style="background-color: #82c408; height: 150px; width: 100%;"></div>
            <!-- 顏色區塊 End -->
            <div class="container py-5">
                <div class="row g-4 mb-0 justify-content-center">
                    <!-- 左邊卡片 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="card border-0 shadow text-center h-100" style="padding-top: 50px;">
                            <!-- 圓形圖片 -->
                            <div class="card-img-top mt-5">
                                <img src="static/img/{{professor[7]}}" class="img-fluid rounded-circle" alt="Image" style="width: 150px; height: 150px; object-fit: cover;">
                            </div>
                            <!-- 資訊 -->
                            <div class="card-body">
                                <h4 class="fw-bold mb-3">{{professor[2]}}</h4>
                                <p class="mb-3">{{professor[6]}}</span></p>
                            </div>
                        </div>
                    </div>
                    <!-- 右邊卡片 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="card border-0 shadow text-center h-100">
                            <!-- 資訊 -->
                            <div class="card-body text-start" style="padding-left: 15%; padding-right: 15%;">
                                <h4 class="fw-bold mb-3" style="text-align: center; padding-top: 20px;">修改個人資料</h4>
                                <form action="{{ url_for('main.update_pro_profile') }}" method="POST" enctype="multipart/form-data">
                                    <p class="mb-3">姓名：<input type="text" class="form-control"  name="name"  value="{{professor[2]}}" required></p>
                                    <p class="mb-3">帳號：<input type="email" class="form-control"  name="account"  value="{{account[1]}}" required></p>
                                    <p class="mb-3">密碼：<input type="text" class="form-control"  name="password"  value="{{account[2]}}" required></p>
                                    <p class="mb-3">職稱：<input type="text" class="form-control"  name="professorship"  value="{{professor[6]}}" required></p>
                                    <p class="mb-3">電子郵件：<input type="email" class="form-control"  name="email"  value="{{professor[3]}}" required></p>
                                    <p class="mb-3">電話：<input type="text" class="form-control"  name="phone"  value="{{professor[4]}}"></p>
                                    <p class="mb-3">照片：<input type="file" class="form-control" name="photo"></p>
                                    <div class="text-center mt-4" style="padding-bottom: 5%;">
                                        <button type="submit" class="btn" style="background-color: #82c408; color: white;">確定</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Single Product End -->
    

        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
            <div class="container py-5">
                <div class="row g-4">
                    <!-- 左邊區塊：中央大學的Google地圖 -->
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-4">
                        <div class="card border-0">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14467.76001603884!2d121.1952988!3d24.9681558!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x346823c1ec904dcb%3A0xcdc129d4455ce456!2z5ZyL56uL5Lit5aSu5aSn5a24!5e0!3m2!1szh-TW!2stw!4v1733202944088!5m2!1szh-TW!2stw" width="100%" height="200" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        
                        </div>
                    </div>
                    <!-- 右邊區塊：中央資管的資訊 -->
                    <div class="col-lg-6">
                        <div class="card border-0 bg-dark">
                            <div class="card-body">
                                <h4 class="text-light mb-3">中央大學資訊管理系</h4>
                                <ul class="list-unstyled text-white">
                                    <li class="mb-2">
                                        <a href="https://im.mgt.ncu.edu.tw/" class="text-white" target="_blank">
                                            <i class="fas fa-link me-2"></i>中央大學資訊管理系系網連結
                                        </a>
                                    </li>
                                    <li class="mb-2">
                                        <i class="fas fa-map-marker-alt me-2"></i>地址：桃園市中壢區中大路300號 管理二館213室
                                    </li>
                                    <li class="mb-2">
                                        <i class="fas fa-phone-alt me-2"></i>系辦電話：(03)422-7151 分機 66500, 66501, 66536, 66559
                                    </li>
                                    <li>
                                        <i class="fas fa-envelope me-2"></i>公務信箱: <a href="mailto:ncu6500@ncu.edu.tw" class="text-white">ncu6500@ncu.edu.tw</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>   

        
        <!-- JavaScript Libraries -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
        <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
        <script src="{{ url_for('static', filename='lib/lightbox/js/lightbox.min.js') }}"></script>
        <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>

        <!-- Template Javascript -->
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </body>

</html>

app/templates/profile_stu_fix.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>NCUIM指導教授管理預約系統</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{{ url_for('static', filename='lib/lightbox/css/lightbox.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">

        <!-- Customized Bootstrap Stylesheet -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    </head>

    <body>

    <!-- Navbar start -->
    <div class="container-fluid fixed-top">
        <div class="container px-0">
            <nav class="navbar navbar-light bg-white navbar-expand-xl">
                <a href="index" class="navbar-brand"><h1 class="text-primary display-6">指導教授管理預約系統</h1></a>
                <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars text-primary"></span>
                </button>
                <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                    <div class="navbar-nav mx-auto">
                        <a href="{{ url_for('main.student_dashboard') }}" class="nav-item nav-link">研究室資訊</a>
                        <a href="{{ url_for('main.appointment_student') }}" class="nav-item nav-link">預約紀錄</a>
                        <a href="{{ url_for('main.mentorship_stu') }}" class="nav-item nav-link">指導邀請</a>
                        <a href="{{ url_for('main.mentorship_stu_detail') }}" class="nav-item nav-link">指導邀請紀錄</a>
                    </div>
                    <div class="d-flex m-3 me-0">
                        <a href="profile_stu" class="my-auto" title="帳號管理">
                            <i class="fas fa-user fa-2x"></i>
                        </a>
                        <a href="{{ url_for('main.logout') }}" class="btn btn-danger ms-3">登出</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->


        <!-- Single Product Start -->
        <div class="container-fluid py-0">
            <!-- 顏色區塊 Start -->
            <div style="background-color: #82c408; height: 150px; width: 100%;"></div>
            <!-- 顏色區塊 End -->
            <div class="container py-5">
                <div class="row g-4 mb-0 justify-content-center">
                    <!-- 左邊卡片 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="card border-0 shadow text-center h-100">
                            <!-- 圓形圖片 -->
                            <div class="card-img-top mt-4">
                                <img src="static/img/{{ student[8] }}" class="img-fluid rounded-circle" alt="Image" style="width: 150px; height: 150px; object-fit: cover;">
                            </div>
                            <!-- 資訊 -->
                            <div class="card-body">
                                <h4 class="fw-bold mb-3">{{ student[0] }}</h4>
                                <div class="card-body text-start" style="padding-left: 15%; padding-right: 15%;">
                                    <p class="mb-3">正備取狀態：<span class="badge rounded-pill {% if '考試' in student[5] %}bg-success{% else %}bg-warning{% endif %}">{{ student[5] }}{{ student[6] }}</span></p>
                                    <p class="mb-3">入學年度：{{ student[4] }}</p>
                                    <p class="mb-3">系所：{{ student[3] }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- 右邊卡片 -->
                    <div class="col-lg-4 col-md-6">
                        <div class="card border-0 shadow text-center h-100">
                            <!-- 資訊 -->
                            <div class="card-body text-start" style="padding-left: 15%; padding-right: 15%;">
                                <h4 class="fw-bold mb-3" style="text-align: center; padding-top: 20px;">修改個人資料</h4>
                                <form action="{{ url_for('main.update_profile') }}" method="POST" enctype="multipart/form-data">
                                    <p class="mb-3">姓名：<input type="text" class="form-control" name="name" value="{{ student[0] }}" required></p>
                                    <p class="mb-3">帳號：<input type="email" class="form-control" name="account" value="{{account[1]}}" required></p>
                                    <p class="mb-3">密碼：<input type="text" class="form-control" name="password" value="{{account[2]}}" required></p>
                                    <p class="mb-3">電子郵件：<input type="email" class="form-control" name="email" value="{{ student[1] }}" required></p>
                                    <p class="mb-3">電話：<input type="text" class="form-control" name="phone" value="{{ student[2] }}"></p>
                                    <p class="mb-3">照片：<input type="file" class="form-control" name="photo"></p>
                                    <div class="text-center mt-4" style="padding-bottom: 5%;">
                                        <button type="submit" class="btn" style="background-color: #82c408; color: white;">確定</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Single Product End -->
    

        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
            <div class="container py-5">
                <div class="row g-4">
                    <!-- 左邊區塊：中央大學的Google地圖 -->
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-4">
                        <div class="card border-0">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14467.76001603884!2d121.1952988!3d24.9681558!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x346823c1ec904dcb%3A0xcdc129d4455ce456!2z5ZyL56uL5Lit5aSu5aSn5a24!5e0!3m2!1szh-TW!2stw!4v1733202944088!5m2!1szh-TW!2stw" width="100%" height="200" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        
                        </div>
                    </div>
                    <!-- 右邊區塊：中央資管的資訊 -->
                    <div class="col-lg-6">
                        <div class="card border-0 bg-dark">
                            <div class="card-body">
                                <h4 class="text-light mb-3">中央大學資訊管理系</h4>
                                <ul class="list-unstyled text-white">
                                    <li class="mb-2">
                                        <a href="https://im.mgt.ncu.edu.tw/" class="text-white" target="_blank">
                                            <i class="fas fa-link me-2"></i>中央大學資訊管理系系網連結
                                        </a>
                                    </li>
                                    <li class="mb-2">
                                        <i class="fas fa-map-marker-alt me-2"></i>地址：桃園市中壢區中大路300號 管理二館213室
                                    </li>
                                    <li class="mb-2">
                                        <i class="fas fa-phone-alt me-2"></i>系辦電話：(03)422-7151 分機 66500, 66501, 66536, 66559
                                    </li>
                                    <li>
                                        <i class="fas fa-envelope me-2"></i>公務信箱: <a href="mailto:ncu6500@ncu.edu.tw" class="text-white">ncu6500@ncu.edu.tw</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>   

        
           <!-- JavaScript Libraries -->
           <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
           <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
           <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
           <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
           <script src="{{ url_for('static', filename='lib/lightbox/js/lightbox.min.js') }}"></script>
           <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>
   
           <!-- Template Javascript -->
           <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </body>

</html>